import re
a="harry123 4pot34ter@"
print("1. \A symbol matches if staring of sting contain that value")
match=re.search(r"\Ahar",a)
print(match)
print("2. \b symbol matches if staring or ending of sting contain that value")
match=re.search(r"\bhar",a)
match1=re.search(r"er\b",a)
print(match,match1)
print("3. \B symbol is exactly opposite in terms of writting code")
match=re.search(r"har\B",a)
match1=re.search(r"\Ber",a)
print(match,match1)
print("4. \d symbol matches if  sting contain decimal value")
match=re.findall(r"\d",a)
print(match)
print("5. \D symbol return everything except Digits")
match=re.findall(r"\D",a)
print(match)
print("6. \s symbol matches if  sting contain WHITE SPACES")
match=re.search(r"\s",a)
print(match)
print("7. \s symbol matches if sting does not contain WHITE SPACES")
match=re.findall(r"\S",a)
print(match)
print("8. \w symbol matches  sting contain alpha numeric values")
match=re.findall(r"\w",a)
print(match)
print("8. \W symbol matches  sting that does not contain alpha numeric values")
match=re.findall(r"\W",a)
print(match)
print("8. \z symbol matches if string ends with the given character")
match=re.search(r"ter@\Z",a)
print(match)